// Authentication Types

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SET_AUTH_REF = "SET_AUTH_REF"
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// Property Types

export const LIST_PROPERTY = "LIST_PROPERTY";
export const LIST_PROPERTY_FAIL = "LIST_PROPERTY_FAIL";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const GET_INTERESTED_PROPERTIES = 'GET_INTERESTED_PROPERTIES';
export const GET_INTERESTED_PROPERTIES_FAILED = "GET_INTERESTED_PROPERTIES_FAILED";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL";
export const UPDATE_PROPERTY = "UPDATE_PROPERTY";
export const UPDATE_PROPERTY_FAIL = "UPDATE_PROPERTY_FAIL";
export const UPDATE_PROPERTY_IMAGE = "UPDATE_PROPERTY_IMAGE";
export const UPDATE_PROPERTY_IMAGE_FAIL = "UPDATE_PROPERTY_IMAGE_FAIL";
export const UPDATE_PROPERTY_PRICE = "UPDATE_PROPERTY_PRICE";
export const UPDATE_PROPERTY_PRICE_FAIL = "UPDATE_PROPERTY_PRICE_FAIL";
export const GET_ALL_PROPERTIES = "GET_ALL_PROPERTIES";
export const GET_USER_PROPERTIES = "GET_USER_PROPERTIES";

// Purchase Types

export const BUY_PROPERTY = "BUY_PROPERTY";
export const BUY_PROPERTY_FAIL = "BUY_PROPERTY_FAIL";
export const PROPERTY_SOLD = "PROPERTY_SOLD";
export const PROPERTY_RESOLD = "PROPERTY_RESOLD";

// Review Types

export const ADD_REVIEW = "ADD_REVIEW";
export const ADD_REVIEW_FAIL = "ADD_REVIEW_FAIL";
export const GET_PROPERTY_REVIEWS = "GET_PROPERTY_REVIEWS";
export const GET_USER_REVIEWS = "GET_USER_REVIEWS";
export const LIKE_REVIEW = "LIKE_REVIEW";
export const GET_HIGHEST_RATED_PROPERTY = "GET_HIGHEST_RATED_PROPERTY";

// Other Types
export const UPDATE_IMAGE = "UPDATE_IMAGE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";