export { default as EditProfile } from "./EditProfile/EditProfile.js"
export { default as ChangePassword } from "./ChangePassword/ChangePassword.js"
export { default as Profile } from "./Profile/Profile.js"
export { default as PurchasedProperty } from "./PurchasedProperty/PurchasedProperty.js"
export { default as Logout } from "./Logout/Logout.js"