export { default as Navbar } from "./Navbar/Navbar"
export { default as Hero } from "./Hero/Hero"
export { default as Benefits} from "./Benefits/Benefits"
export { default as Property } from "./Property/Property"
export { default as Tenants } from "./ForTenants/Tenants"
export { default as CTA } from "./CTA/CTA"
export { default as Footer } from "./Footer/Footer"