export { default as LandingPage } from "./LandingPage/LandingPage"
export { default as Login } from "./Login/Login"
export { default as Signin } from "./Signin/Signin"
export { default as Seller } from "./Seller/SellerDashboard"
export { default as User } from "./User/UserDashboard"
export { default as CategoryPage } from "./CategoryPage/CategoryPage"
export { default as Cart } from "./Cart/Cart"